new_ssh_port: 2222

package_needed: 
  - openssh-server
  - unattended-upgrades
  - ufw
  - fail2ban
  - selinux-basics
  - python3-selinux
  - python3-semanage
  - selinux-policy-default
  - policycoreutils
  - auditd
