project_name: tsukatsuki-test
local_project_path: /home/alie/code/golang/tsukatsuki-test
remote_project_path: /home/tsukatsuki/tsukatsuki-test
generated_folder_name: deploy
ssh_key_folder_name: "key"
compose_file_name: "docker-compose.yaml"

new_ssh_port: 2222

# This will be used for testing, for now
setup_user: setup