---
- name: Converge
  hosts: setup
  gather_facts: true
  vars_files: 
  - ../../group_vars/all.yaml
  roles: 
    # - role: ../../roles/debug
    - role: ../../roles/common
    - role: ../../roles/security
    - role: ../../roles/docker
    # - role: ../../roles/deployment

