name: CI
on:
  push:
    branches: 
      - main
      - fix/*
      - feat/*
  pull_request:
    branches:
      - main


jobs:
    molecule-test: 
      runs-on: ubuntu-latest
      strategy:
        matrix:
          distro:
            - ubuntu2404
            - ubuntu2204
            - debian13
            - debian12

      steps: 
        - uses: actions/checkout@v5

        - name: Set up Python 3.
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'

        - name: Install test dependencies.
          run: pip3 install ansible molecule molecule-plugins[docker] docker

        - name: Debug
          working-directory: ./deploy/ansible
          run: pwd

        - name: Run Molecule tests.
          run: molecule test
          working-directory: ./deploy/ansible
          env:
            PY_COLORS: '1'
            ANSIBLE_FORCE_COLOR: '1'
            MOLECULE_DISTRO: ${{ matrix.distro }}


  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v5

  #     - name: Set up Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: '1.24.x'
      
  #     - name: Display Go version
  #       run: go version

  #     - name: Install dependencies
  #       run: go mod download

  #     - name: Verify dependencies
  #       run: go mod verify

  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v8
  #       with:
  #         version: latest
  #         args: --timeout=5m

  # builds:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v5

  #     - name: Set up Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: '1.24.x'
      
  #     - name: Display Go version
  #       run: go version

  #     - name: Install dependencies
  #       run: go mod download

  #     - name: Verify dependencies
  #       run: go mod verify

  #     - name: Build application
  #       run: go build -ldflags='-s' -o=./bin/api ./cmd/api

